# Generated by Django 6.0.5 on 2026-06-01 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="DNI / Cédula"
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                (
                    "grupo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("domicilio", models.CharField(blank=True, max_length=200)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("alergias", models.TextField(blank=True)),
                ("antecedentes", models.TextField(blank=True)),
                ("medicacion_habitual", models.TextField(blank=True)),
                ("obra_social", models.CharField(blank=True, max_length=100)),
                ("nro_afiliado", models.CharField(blank=True, max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SignosVitales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "presion_sistolica",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Presión sistólica (mmHg)"
                    ),
                ),
                (
                    "presion_diastolica",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Presión diastólica (mmHg)"
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="FC (lpm)"
                    ),
                ),
                (
                    "frecuencia_respiratoria",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="FR (rpm)"
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "saturacion_o2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="SatO₂ (%)"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "talla",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Talla (cm)",
                    ),
                ),
                (
                    "motivo_consulta",
                    models.TextField(verbose_name="Motivo de consulta"),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signos_vitales",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "tomados_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signos_tomados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signos vitales",
                "verbose_name_plural": "Signos vitales",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
