# Generated by Django 6.0.5 on 2026-06-02 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consulta", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(default="Consulta médica", max_length=200),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_deb", "Tarjeta débito"),
                            ("tarjeta_cred", "Tarjeta crédito"),
                            ("transferencia", "Transferencia"),
                            ("obra_social", "Obra social"),
                            ("sin_cargo", "Sin cargo"),
                        ],
                        default="efectivo",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("impreso", models.BooleanField(default=False)),
                (
                    "nro_recibo",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "turno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="consulta.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
