# Generated by Django 6.0.5 on 2026-06-01 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "anamnesis",
                    models.TextField(
                        verbose_name="Anamnesis / Historia de la enfermedad"
                    ),
                ),
                (
                    "examen_fisico",
                    models.TextField(blank=True, verbose_name="Examen físico"),
                ),
                ("diagnostico_principal", models.CharField(max_length=200)),
                ("diagnosticos_secundarios", models.TextField(blank=True)),
                (
                    "cie10",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código CIE-10"
                    ),
                ),
                ("tratamiento", models.TextField(verbose_name="Plan de tratamiento")),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True, verbose_name="Indicaciones al paciente"
                    ),
                ),
                ("proxima_consulta", models.DateField(blank=True, null=True)),
                (
                    "derivacion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Derivación a especialista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia clínica",
                "verbose_name_plural": "Historias clínicas",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="RecetaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicamento", models.CharField(max_length=200)),
                (
                    "dosis",
                    models.CharField(
                        max_length=100, verbose_name="Dosis / Concentración"
                    ),
                ),
                (
                    "forma",
                    models.CharField(
                        help_text="ej: comprimidos, jarabe, inyectable",
                        max_length=100,
                        verbose_name="Forma farmacéutica",
                    ),
                ),
                (
                    "posologia",
                    models.CharField(
                        help_text="ej: 1 comprimido cada 8 horas por 7 días",
                        max_length=200,
                        verbose_name="Posología",
                    ),
                ),
                ("cantidad", models.CharField(blank=True, max_length=50)),
                ("instrucciones", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("espera", "En espera"),
                            ("llamado", "Llamado"),
                            ("atencion", "En atención"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="espera",
                        max_length=15,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(default=django.utils.timezone.now)),
                ("hora_llamado", models.DateTimeField(blank=True, null=True)),
                ("hora_inicio_atencion", models.DateTimeField(blank=True, null=True)),
                ("hora_fin", models.DateTimeField(blank=True, null=True)),
                ("numero", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ["fecha_hora"],
            },
        ),
    ]
