# Generated by Django 6.0.5 on 2026-06-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consulta", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historiaclinica",
            name="medico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historias_clinicas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recetamedicamento",
            name="historia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receta_items",
                to="consulta.historiaclinica",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="medico",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turnos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turnos",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="signos",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turno",
                to="pacientes.signosvitales",
            ),
        ),
        migrations.AddField(
            model_name="historiaclinica",
            name="turno",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historia",
                to="consulta.turno",
            ),
        ),
    ]
